// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPIuduuDAS65nPtQAtqIeV71oHLUS3yU',
    appId: '1:307390543522:web:b9ca171f47d84bf02889fb',
    messagingSenderId: '307390543522',
    projectId: 'chat-app-3d604',
    authDomain: 'chat-app-3d604.firebaseapp.com',
    storageBucket: 'chat-app-3d604.appspot.com',
    measurementId: 'G-EZCDN32SHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkOaHve7BXsh0Nk4Bnl8NZd5FS-dPouY',
    appId: '1:307390543522:android:0e59bbad41a43c672889fb',
    messagingSenderId: '307390543522',
    projectId: 'chat-app-3d604',
    storageBucket: 'chat-app-3d604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLN_mZhH8CSOhe79MrPIVrQP4Vk_cjJ0',
    appId: '1:307390543522:ios:9761913a7cde0d042889fb',
    messagingSenderId: '307390543522',
    projectId: 'chat-app-3d604',
    storageBucket: 'chat-app-3d604.appspot.com',
    iosBundleId: 'com.example.cubitchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZLN_mZhH8CSOhe79MrPIVrQP4Vk_cjJ0',
    appId: '1:307390543522:ios:9761913a7cde0d042889fb',
    messagingSenderId: '307390543522',
    projectId: 'chat-app-3d604',
    storageBucket: 'chat-app-3d604.appspot.com',
    iosBundleId: 'com.example.cubitchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxPIuduuDAS65nPtQAtqIeV71oHLUS3yU',
    appId: '1:307390543522:web:bc3d48ddd500c1182889fb',
    messagingSenderId: '307390543522',
    projectId: 'chat-app-3d604',
    authDomain: 'chat-app-3d604.firebaseapp.com',
    storageBucket: 'chat-app-3d604.appspot.com',
    measurementId: 'G-3Z2FK9YNX5',
  );

}